### ISSUE TITLE
Map doesn't render in Safari on Mac OS

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#113] opened 2018-09-05 17:49 UTC
On Safari browser: 
https://events.handsupfoundation.org/singing-for-syrians-2018/flagship-carol-service/
![screen shot 2018-09-05 at 18 31 29](https://user-images.githubusercontent.com/41363663/45110368-f5ce7280-b139-11e8-8f79-5d63e0eea7f1.png)

on same Mac in Chrome:
<img width="1302" alt="screen shot 2018-09-05 at 18 32 17" src="https://user-images.githubusercontent.com/41363663/45110407-0c74c980-b13a-11e8-89f0-1cd3a4bd87b6.png">

Perhaps related, in Safari I also cannot:
Sign-in to Gmail. Screen goes dark (like a modal will appear) and pop-up dialog doesn't appear. (I think Safari now blocks pop-ups by default. Obvs I personally can disable, but would be a wider-ranging issue. https://www.technipages.com/safari-popup-blocker)

See the credit card number field . I just get some text.  See screenshot. 
![screen shot 2018-09-05 at 18 48 49](https://user-images.githubusercontent.com/41363663/45111252-6aa2ac00-b13c-11e8-9983-8253ae9a1d65.png)

**Comment by samuelcolvin** [comment] 2018-09-11 15:34
duplicate of other safari issue #108

**Closed by samuelcolvin** 2018-09-11 15:34 UTC
